name: lms
description: Clean LMS App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ^2.10.0

dependencies:
  
  cupertino_icons: ^1.0.4
  smooth_page_indicator: ^1.0.0+2
  flutter_riverpod: ^1.0.4
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.4
  hooks_riverpod: ^1.0.4
  go_router: ^4.2.8
  pinput: ^2.2.12
  flutter_native_splash: ^2.2.9
  percent_indicator: ^4.2.2
  dropdown_button2: ^1.8.2
  persistent_bottom_nav_bar_v2: ^4.2.5
  date_picker_timeline: ^1.2.3

  flutter:
    sdk: flutter
  equatable: any
  json_annotation: any
  flutter_localizations:
    sdk: flutter
  json_serializable: any
  freezed_annotation: ^2.1.0
  rxdart: ^0.27.5
  sqflite: ^2.0.3+1
  state_notifier: ^0.7.0
  intl: ^0.17.0
  dio: ^4.0.6
  flutter_secure_storage: ^6.0.0
  get_storage: ^2.0.3
  logger: ^1.1.0
  firebase_core: ^1.23.0
  get_it: ^7.2.0
  firebase_messaging: ^13.0.3
  device_info_plus: ^4.1.2
  readmore: ^2.2.0
dev_dependencies:
  change_app_package_name: ^1.1.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  mockito: ^5.3.0
  


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/fonts/
    - assets/images/
    - assets/images/ProfileCards/
    - assets/icons/


fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Medium.ttf
        style: normal